[hololens]
container = "ghcr.io/hologit/lenses/compass:latest"

[hololens.input]
root = "site-root"
files = [
    "sass/**",
    "fonts/**",
    "img/**"
]

# optional and stripped from holospec:
[hololens.output]
root = "site-root/css" # defaults to hololens.root
merge = "overlay" # overlay / underlay / replace, defaults to overlay
