[hololens]
container = "ghcr.io/hologit/lenses/sencha-pages:latest"

[hololens.input]
root = "sencha-workspace"
files = [
    "ext/**",
    "pages/**"
]

# optional and stripped from holospec:
[hololens.output]
root = "site-root/js/pages" # defaults to hololens.root
merge = "overlay" # overlay / underlay / replace, defaults to overlay
